Написала разметку главной страницы и страницы каталога проекта Device
htmlacademy-htmlcss/1838119-device-32 pull request #2
Opened 2021-09-28 11:49 UTC by Littlberdova

2021-09-29 07:07 UTC, craz3r requested changes

2021-09-29 07:07 UTC, craz3r commented on index.html
> +      <img src="#" alt="Логотип HTML Академии">
Логотип htmlacademy должны вести на сайт академии (см макет)

2021-09-29 07:07 UTC, craz3r commented on catalog.html
> +                        <button name="go-to-goodspage" type="button"> <span class="visually-hidden"> Расскрыть католог
Расскрыть -> раскрыть (орфографическая ошибка)

2021-09-29 07:07 UTC, craz3r commented on catalog.html
> +            <ol class="links-onthepage-list">
Нумерованный список здесь можно заменить на ненумерованный. Также весь блок с ссылками неплохо обернуть в nav

2021-09-29 07:07 UTC, craz3r commented on catalog.html
> +                <button class="button-up" type="button"> <span class="visually-hidden">Наверх каталога</span></button>
Эти кнопки нужны для сортировки "По возрастанию\убыванию", а не для перемещения по каталогу, они не являются частью формы с селектом

2021-09-29 07:07 UTC, craz3r commented on catalog.html
> +                    <span class="product-card-price"> 500 ₽</span>
Также на всех продуктах присуствует кнопка "Подробнее"

2021-10-02 10:29 UTC, Littlberdova commented on catalog.html
> +            <ol class="links-onthepage-list">
исправила

2021-10-02 10:30 UTC, Littlberdova commented on catalog.html
> +            <ol class="links-onthepage-list">
исправила

2021-10-02 10:37 UTC, Littlberdova commented on catalog.html
> +                        <button name="go-to-goodspage" type="button"> <span class="visually-hidden"> Расскрыть католог
исправила

2021-10-02 10:41 UTC, Littlberdova commented on catalog.html
> +                <button class="button-up" type="button"> <span class="visually-hidden">Наверх каталога</span></button>
исправила

2021-10-02 10:50 UTC, Littlberdova commented on catalog.html
> +                    <span class="product-card-price"> 500 ₽</span>
исправила

2021-10-02 10:55 UTC, Littlberdova commented on index.html
> +    <img src="#" alt="Логотип компании">
исправила

2021-10-02 10:56 UTC, Littlberdova commented on index.html
> +        <th class="row-name">
исправила

2021-10-02 11:29 UTC, Littlberdova commented on index.html
> +        <a class="more-detailed" href="#"> Подробнее</a>
исправила

2021-10-02 11:41 UTC, Littlberdova commented on index.html
> +    </section>
добавила

2021-10-02 11:48 UTC, Littlberdova commented on index.html
> +      <h3 class="section-header"> Доставка </h3>
исправила

2021-10-02 11:50 UTC, Littlberdova commented on index.html
> +      <b> Доставим редкий товар под заказ </b>
исправила

2021-10-02 11:51 UTC, Littlberdova commented on index.html
> +        <ol class="work-day-list">
исправила

2021-10-02 11:53 UTC, Littlberdova commented on index.html
> +    <img src="#" alt="Логотип компании">
исправила

2021-10-02 11:57 UTC, Littlberdova commented on index.html
> +        <li class="socialmedia-item"> <a class="socialmedia-link" href="#"> <span class="visually-hidden"> Facebook
добавила

2021-10-02 11:58 UTC, Littlberdova commented on index.html
> +      <img src="#" alt="Логотип HTML Академии">
добавила

2021-10-03 14:25 UTC, merged