Добавила базовую стилизацию и графику
htmlacademy-htmlcss/1838119-device-32 pull request #3
Opened 2021-10-05 05:54 UTC by Littlberdova

2021-10-05 13:46 UTC, craz3r requested changes
Summary: Исправить отступы, сейчас читать код неудобно. Удалить все глобальные стили тегов, и заменить на классы

2021-10-05 13:46 UTC, craz3r commented on styles/styles.css
> +background-color: #FFE17F;
Старайтесь соблюдать отступы в стилях
Также строкой ниже лишний символ точки с запятой

2021-10-05 13:46 UTC, craz3r commented on styles/styles.css
> +p b {
Глобальные стили тегов не допустимы, см https://up.htmlacademy.ru/htmlcss/32/criteries#CSS-02

2021-10-07 04:28 UTC, Littlberdova commented on styles/styles.css
> +p b {
исправила

2021-10-07 07:48 UTC, merged