Декоративные элементы и состояния
htmlacademy-htmlcss/1838119-device-32 pull request #7
Opened 2021-11-06 15:04 UTC by Littlberdova

Что-то применить состояния ко многим элементам у меня не выходит.

2021-11-07 12:40 UTC, craz3r requested changes

2021-11-07 12:40 UTC, craz3r commented on styles/styles.css
> +.slide-description .button:active { /*А почему, когда я нажимаю на кнопку, у меня и состояние фокуса и активности вместе применяются? Это корректно?*/
Используйте focus-visible

2021-11-07 12:40 UTC, craz3r commented on styles/styles.css
> +goods-catalog-item-link:focus .goods-catalog-item { /*Не получается*/
точка пропущена в названии класса

2021-11-07 12:40 UTC, craz3r commented on styles/styles.css
> +.goods-catalog-item-link:hover {  /*Не получается*/
Что именно? Все работает так как написано, применяется фоновый цвет при наведении

2021-11-07 12:40 UTC, craz3r commented on styles/styles.css
> +    fill: rgba(54, 54, 54, 0.5);
Удалите из разметки атрибут fill у path внутри свг, тогда будет работать

2021-11-07 12:40 UTC, craz3r commented on styles/styles.css
> +    border: 5px solid #AF4FFF;  /*Не применяется*/
Вы пытаетесь применить фокус на див, поэтому он не работает

2021-11-07 12:40 UTC, craz3r commented on styles/styles.css
> +    fill: #FFFFFF; /*Не получается изменить цвет логотипа*/
Потому что он подключен как внешний ресурс через тег img, чтобы он поменялся нужно вставлять свг код в страницу напрямую

2021-11-07 12:40 UTC, craz3r commented on styles/styles.css
> +    fill: rgba(255, 255, 255, 0.5); /*  Тоже не получается изменить цвет логотипа*/
Решение в коменте выше

2021-11-07 12:40 UTC, craz3r commented on styles/styles.css
> +    color: rgba(0, 0, 0, 1);
В основном правиле прописан черный цвет, соответственно вы пытаетесь изменить черный цвет на черный цвет, поэтому не работает

2021-11-07 12:40 UTC, craz3r commented on styles/styles.css
> +    fill:rgba(0, 0, 0, 0.3);
Удалите атрибут fill у path в разметке внутри свг

2021-11-07 12:40 UTC, craz3r commented on styles/styles.css
> +    background-color: #FFC700;
Чтобы градиент пропал перепишите свойство background целиком, background - составное свойство и сейчас и градиент и цвет работают вместе

2021-11-07 12:40 UTC, craz3r commented on styles/styles.css
> +    fill:rgba(0, 0, 0, 0.8); /*Не меняется цвет svg*/
См комментарии выше

2021-11-07 12:40 UTC, craz3r commented on styles/styles.css
> +   text-align: center; /*А почему текст в кружочке на встает в центр кружочка?*/
Чтобы отцентровать текст внутри блока по вертикали попробуйте поиграться с высотой строки

2021-11-07 12:40 UTC, craz3r commented on styles/styles.css
> +.product-card:focus .product-description-container {
Фокус по умолчанию работает только на интерактивных элементах - ссылках, кнопках и элементах форм. Чтобы сделать другие теги интерактивными почитайте про атрибут tabIndex

2021-11-07 12:40 UTC, craz3r commented on styles/styles.css
> +.pagination-link:focus { /*Не фокусируется на Вперед и 1*/
Добавьте этим ссылкам атрибут href - сейчас его нет

2021-11-07 12:40 UTC, craz3r commented on styles/styles.css
> +    border: 5px solid #AF4FFF; /*Правая часть границы не появляется, хотя я поставила border-box*/
Используйте для фокуса свойство outline или box-shadow - они не влияют на блочную модель и блоки при фокусе не будут прыгать

2021-11-07 12:40 UTC, craz3r commented on styles/styles.css
> +.product-card-link:focus .product-description-container { /*Не понимаю, что я делаю не так*/
Селектор написан неправильно - .product-description-container не является потомком .product-card-link

2021-11-08 09:03 UTC, Littlberdova commented on styles/styles.css
> +.slide-description .button:active { /*А почему, когда я нажимаю на кнопку, у меня и состояние фокуса и активности вместе применяются? Это корректно?*/
сделала

2021-11-08 09:18 UTC, Littlberdova commented on styles/styles.css
> +    fill: rgba(54, 54, 54, 0.5);
получилось

2021-11-08 09:28 UTC, Littlberdova commented on styles/styles.css
> +   text-align: center; /*А почему текст в кружочке на встает в центр кружочка?*/
Получилось

2021-11-08 09:59 UTC, Littlberdova commented on styles/styles.css
> +.product-card:focus .product-description-container {
попробовала, почти получилось реализовать

2021-11-08 09:59 UTC, Littlberdova commented on styles/styles.css
> +.pagination-link:focus { /*Не фокусируется на Вперед и 1*/
добавила

2021-11-08 10:02 UTC, Littlberdova commented on styles/styles.css
> +    border: 5px solid #AF4FFF; /*Правая часть границы не появляется, хотя я поставила border-box*/
поняла

2021-11-08 10:03 UTC, Littlberdova commented on styles/styles.css
> +.product-card-link:focus .product-description-container { /*Не понимаю, что я делаю не так*/
убрала

2021-11-08 10:19 UTC, Littlberdova commented on styles/styles.css
> +goods-catalog-item-link:focus .goods-catalog-item { /*Не получается*/
исправила

2021-11-08 10:19 UTC, Littlberdova commented on styles/styles.css
> +.goods-catalog-item-link:hover {  /*Не получается*/
исправила

2021-11-08 10:24 UTC, Littlberdova commented on styles/styles.css
> +    fill:rgba(0, 0, 0, 0.3);
убрала

2021-11-08 12:26 UTC, Littlberdova commented on styles/styles.css
> +    background-color: #FFC700;
исправила

2021-11-08 13:33 UTC, Littlberdova commented on styles/styles.css
> +    fill:rgba(0, 0, 0, 0.8); /*Не меняется цвет svg*/
исправила

2021-11-10 14:17 UTC, merged